{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting auto display for cadquery Workplane and Shape\n"
     ]
    }
   ],
   "source": [
    "import cadquery as cq\n",
    "import jupyter_cadquery\n",
    "\n",
    "jupyter_cadquery.set_defaults(ortho=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dataclasses import dataclass\n",
    "import math\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class HeadParams:\n",
    "    circumference: float\n",
    "\n",
    "    @property\n",
    "    def diameter(self):\n",
    "        return self.circumference / math.pi\n",
    "\n",
    "    @property\n",
    "    def radius(self):\n",
    "        return self.diameter / 2\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class HeadbandParams:\n",
    "    # The thickness of the headband\n",
    "    thickness: float\n",
    "    # The height of the headband\n",
    "    height: float\n",
    "    # The length the headband extends past the arc\n",
    "    # As this increases it takes on a horseshoe shape\n",
    "    extension_length: float\n",
    "    # The radius of the attachment loops\n",
    "    attachment_radius: float\n",
    "    # The thickness of the attachment loops\n",
    "    attachment_thickness: float\n",
    "    # Positions of  Kemo tweeters (degrees relative to 0˚ = front)\n",
    "    tweeter_positions: list[float]\n",
    "    # How far forward to push the tweeters in the headband\n",
    "    tweeter_indent: float\n",
    "    # Microphone clip height\n",
    "    mic_clip_height: float\n",
    "    # Microphone clip clearance (~width of mic board)\n",
    "    mic_clip_clearance: float\n",
    "    # Microphone clip protrusion from side\n",
    "    mic_clip_protrusion: float\n",
    "    # Microphone clip thickness\n",
    "    mic_clip_thickness: float\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class HeadboxParams:\n",
    "    # The depth of the headbox\n",
    "    depth: float\n",
    "    # The thickness of the control board holder\n",
    "    wall_thickness: float\n",
    "    # The peneration of the head into the headbox\n",
    "    head_penetration: float\n",
    "    # The cutout cylinder penetration\n",
    "    deep_cutout_penetration: float\n",
    "    # The radius of the cutout cylinder\n",
    "    deep_cutout_radius: float\n",
    "    # The strap cutout width\n",
    "    strap_cutout_width: float\n",
    "    # The strap cutout height\n",
    "    strap_cutout_height: float\n",
    "    # The strap cutout depth\n",
    "    strap_cutout_depth: float\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class ControlBoardParams:\n",
    "    # The width of the control board\n",
    "    width: float\n",
    "    # The height of the control board\n",
    "    height: float\n",
    "    # The depth of the control board\n",
    "    depth: float\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class BatteryParams:\n",
    "    # The width of the battery\n",
    "    width: float\n",
    "    # The height of the battery\n",
    "    height: float\n",
    "    # The depth of the battery\n",
    "    depth: float\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class HeadsetParams:\n",
    "    front_head: HeadParams\n",
    "    back_head: HeadParams\n",
    "    headband: HeadbandParams\n",
    "    headbox: HeadboxParams\n",
    "    battery: BatteryParams\n",
    "    control_board: ControlBoardParams\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "front_head = HeadParams(circumference=470)\n",
    "back_head = HeadParams(circumference=560)\n",
    "\n",
    "headband = HeadbandParams(\n",
    "    thickness=6,\n",
    "    height=45,\n",
    "    extension_length=20,\n",
    "    attachment_radius=10,\n",
    "    attachment_thickness=3,\n",
    "    tweeter_positions=[-60, 0, 60],\n",
    "    tweeter_indent=1,\n",
    "    mic_clip_height=6,\n",
    "    mic_clip_protrusion=10,\n",
    "    mic_clip_clearance=2.75,\n",
    "    mic_clip_thickness=2,\n",
    ")\n",
    "\n",
    "headbox = HeadboxParams(\n",
    "    depth=8,\n",
    "    wall_thickness=2,\n",
    "    head_penetration=20,\n",
    "    deep_cutout_penetration=7,\n",
    "    deep_cutout_radius=7,\n",
    "    strap_cutout_depth=7,\n",
    "    strap_cutout_height=15,\n",
    "    strap_cutout_width=5,\n",
    ")\n",
    "\n",
    "battery = BatteryParams(\n",
    "    width=62,\n",
    "    height=39,\n",
    "    depth=9,\n",
    ")\n",
    "\n",
    "control_board = ControlBoardParams(\n",
    "    width=90,\n",
    "    height=64,\n",
    "    depth=18,\n",
    ")\n",
    "\n",
    "headset = HeadsetParams(\n",
    "    front_head=front_head,\n",
    "    back_head=back_head,\n",
    "    headband=headband,\n",
    "    headbox=headbox,\n",
    "    battery=battery,\n",
    "    control_board=control_board,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "5307b862775d48aa801d8de041eae4f6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "CadViewerWidget(anchor=None, cad_width=800, glass=False, height=600, pinning=False, theme='light', title=None,…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<div></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "def create_headbox_arc(\n",
    "    width: float,\n",
    "    height: float,\n",
    "    head_radius: float,\n",
    "    head_radius_penetration: float,\n",
    "):\n",
    "    arc_box = cq.Workplane(\"XZ\").box(\n",
    "        width,\n",
    "        height,\n",
    "        head_radius_penetration,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    arc_cyclinder = (\n",
    "        cq.Workplane(\"XY\", origin=(0, head_radius - head_radius_penetration))\n",
    "        .circle(head_radius)\n",
    "        .extrude(height, both=True)\n",
    "    )\n",
    "    y_depth = arc_box.faces(\"<Y\").val().Center().y\n",
    "    return arc_box.cut(arc_cyclinder).translate((0, -y_depth))\n",
    "\n",
    "\n",
    "def create_cutout_cylinder(\n",
    "    radius: float,\n",
    "    height: float,\n",
    "    penetration: float,\n",
    "):\n",
    "    return (\n",
    "        cq.Workplane(\"XY\", origin=(0, radius - penetration))\n",
    "        .circle(radius)\n",
    "        .extrude(height / 2, both=True)\n",
    "    )\n",
    "\n",
    "\n",
    "def create_battery_holder(\n",
    "    battery_width: float,\n",
    "    battery_height: float,\n",
    "    battery_depth: float,\n",
    "    container_width: float,\n",
    "    container_height: float,\n",
    "):\n",
    "    outer_box = cq.Workplane(\"XZ\").box(\n",
    "        container_width,\n",
    "        container_height,\n",
    "        battery_depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    inner_box = cq.Workplane(\"XZ\").box(\n",
    "        battery_width,\n",
    "        battery_height,\n",
    "        battery_depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    return outer_box.cut(inner_box)\n",
    "\n",
    "\n",
    "def create_control_board_holder(\n",
    "    control_board_width: float,\n",
    "    control_board_height: float,\n",
    "    control_board_depth: float,\n",
    "    container_width: float,\n",
    "    container_height: float,\n",
    "    wall_thickness: float,\n",
    "    ethernet_cutout_width: float = 20,\n",
    "):\n",
    "    outer_box = cq.Workplane(\"XZ\").box(\n",
    "        container_width,\n",
    "        container_height,\n",
    "        control_board_depth + wall_thickness,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "\n",
    "    inner_box = (\n",
    "        cq.Workplane(\"XZ\")\n",
    "        .box(\n",
    "            control_board_width,\n",
    "            control_board_height + 2 * wall_thickness,\n",
    "            control_board_depth,\n",
    "            centered=(True, True, False),\n",
    "        )\n",
    "        .translate((0, 0, wall_thickness))\n",
    "    )\n",
    "    ethernet_x = (control_board_width - ethernet_cutout_width) / 2\n",
    "    ethernet_z = -(control_board_height - ethernet_cutout_width) / 2 - wall_thickness\n",
    "    ethernet_cutout = (\n",
    "        cq.Workplane(\"XZ\")\n",
    "        .box(\n",
    "            ethernet_cutout_width,\n",
    "            ethernet_cutout_width,\n",
    "            control_board_depth,\n",
    "            centered=(True, True, False),\n",
    "        )\n",
    "        .translate((ethernet_x, 0, ethernet_z))\n",
    "    )\n",
    "    return outer_box.cut(inner_box).cut(ethernet_cutout)\n",
    "\n",
    "\n",
    "def bind_to_top_surface(box: cq.Workplane, target: cq.Workplane, cut: bool = False):\n",
    "    box_y_extent = box.faces(\"<Y\").val().Center().y\n",
    "    target_y_extent = target.faces(\"<Y\" if cut else \">Y\").val().Center().y\n",
    "    target = target.translate((0, box_y_extent - target_y_extent, 0))\n",
    "    if cut:\n",
    "        return box.cut(target)\n",
    "    else:\n",
    "        return box.union(target)\n",
    "\n",
    "\n",
    "def create_headbox(hs: HeadsetParams):\n",
    "    headbox_height = 2 * hs.headbox.wall_thickness + hs.control_board.height\n",
    "    headbox_width = 2 * hs.headbox.wall_thickness + hs.control_board.width\n",
    "    arc = create_headbox_arc(\n",
    "        width=headbox_width,\n",
    "        height=headbox_height,\n",
    "        head_radius=hs.back_head.radius,\n",
    "        head_radius_penetration=hs.headbox.head_penetration,\n",
    "    )\n",
    "    box = cq.Workplane(\"XZ\").box(\n",
    "        headbox_width,\n",
    "        headbox_height,\n",
    "        hs.headbox.depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    cutout_cylinder = create_cutout_cylinder(\n",
    "        radius=hs.headbox.deep_cutout_radius,\n",
    "        height=3 * hs.headbox.strap_cutout_height,\n",
    "        penetration=hs.headbox.deep_cutout_penetration,\n",
    "    )\n",
    "    box = box.union(arc).cut(cutout_cylinder)\n",
    "    box = bind_to_top_surface(\n",
    "        box=box,\n",
    "        target=cq.Workplane(\"XZ\").box(\n",
    "            headbox_width,\n",
    "            hs.headbox.strap_cutout_height,\n",
    "            hs.headbox.strap_cutout_depth,\n",
    "            centered=(True, True, True),\n",
    "        ),\n",
    "        cut=True,\n",
    "    )\n",
    "    box = bind_to_top_surface(\n",
    "        box=box,\n",
    "        target=create_battery_holder(\n",
    "            battery_width=hs.battery.width,\n",
    "            battery_height=hs.battery.height,\n",
    "            battery_depth=hs.battery.depth,\n",
    "            container_width=headbox_width,\n",
    "            container_height=headbox_height,\n",
    "        ),\n",
    "    )\n",
    "    box = bind_to_top_surface(\n",
    "        box=box,\n",
    "        target=create_control_board_holder(\n",
    "            control_board_width=hs.control_board.width,\n",
    "            control_board_height=hs.control_board.height,\n",
    "            control_board_depth=hs.control_board.depth,\n",
    "            container_width=headbox_width,\n",
    "            container_height=headbox_height,\n",
    "            wall_thickness=hs.headbox.wall_thickness,\n",
    "        ),\n",
    "    )\n",
    "    return box\n",
    "\n",
    "\n",
    "create_headbox(headset)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "robin-headset-pueixTSH-py3.11",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
