{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "import jupyter_cadquery\n",
    "\n",
    "jupyter_cadquery.set_defaults(ortho=False, glass=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_half_torus(thickness: float, radius: float):\n",
    "    return (\n",
    "        cq.Workplane(\"XZ\", origin=(radius, radius, 0))\n",
    "        .circle(thickness / 2)\n",
    "        .revolve(180, (-radius, 0, 0), (-radius, -1, 0))\n",
    "        .rotateAboutCenter((0, 1, 0), 90)\n",
    "        .translate((0, -radius, 0))\n",
    "    )\n",
    "\n",
    "create_half_torus(1, 3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_headband_arc(\n",
    "    radius: float,\n",
    "    thickness: float,\n",
    "    extension: float,\n",
    "    height: float,\n",
    "):\n",
    "    inner_radius = radius - thickness\n",
    "    wp = (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .moveTo(radius, 0)\n",
    "        .threePointArc((0, radius), (-radius, 0))\n",
    "        .vLineTo(-extension)\n",
    "        .hLineTo(-inner_radius)\n",
    "        .vLineTo(0)\n",
    "        .threePointArc((0, inner_radius), (inner_radius, 0))\n",
    "        .vLineTo(-extension)\n",
    "        .hLineTo(radius)\n",
    "        .vLineTo(0)\n",
    "        .close()\n",
    "    )\n",
    "    return wp.extrude(height)\n",
    "\n",
    "\n",
    "band = create_headband_arc(\n",
    "    radius=8.5,\n",
    "    thickness=0.6,\n",
    "    extension=3,\n",
    "    height=3.5,\n",
    ")\n",
    "loop = create_half_torus(0.3, 1)\n",
    "for face in band.faces(\"<Y\").vals():\n",
    "    face_loop = loop.translate(face.Center())\n",
    "    band = band.union(face_loop)\n",
    "band"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_screw_mount(\n",
    "    hole_diameter: float,\n",
    "    hole_padding: float,\n",
    "    depth: float,\n",
    "):\n",
    "    inner_radius = hole_diameter / 2\n",
    "    outer_radius = inner_radius + hole_padding\n",
    "    outer_cylinder = cq.Workplane(\"XZ\").circle(outer_radius).extrude(depth)\n",
    "    inner_cylinder = cq.Workplane(\"XZ\").circle(inner_radius).extrude(depth)\n",
    "    return outer_cylinder.cut(inner_cylinder)\n",
    "\n",
    "\n",
    "create_screw_mount(1, 0.5, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_strap_guide(height: float, width: float, depth: float, strap_clearance: float):\n",
    "    padding = depth - strap_clearance\n",
    "    assert padding >= 0.1\n",
    "    outer_rect = (\n",
    "        cq.Workplane(\"YZ\")\n",
    "        .rect(strap_clearance + padding * 2, height + padding * 2, centered=(True, True))\n",
    "        .extrude(width)\n",
    "    )\n",
    "    inner_rect = (\n",
    "        cq.Workplane(\"YZ\")\n",
    "        .rect(strap_clearance + padding * 2, height, centered=(True, True))\n",
    "        .extrude(width)\n",
    "        .translate((0, padding, 0))\n",
    "    )\n",
    "    y_offset = outer_rect.faces(\">Y\").val().Center().y\n",
    "    return outer_rect.cut(inner_rect).translate((0, -y_offset, 0)) \n",
    "\n",
    "\n",
    "create_strap_guide(2, 1, 0.4, 0.2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Tuple\n",
    "\n",
    "\n",
    "def create_arc(\n",
    "    width: float,\n",
    "    height: float,\n",
    "    head_radius: float,\n",
    "    head_radius_penetration: float,\n",
    "):\n",
    "    arc_box = cq.Workplane(\"XZ\").box(\n",
    "        width, height, head_radius_penetration, centered=(True, True, False)\n",
    "    )\n",
    "    arc_cyclinder = (\n",
    "        cq.Workplane(\"XY\", origin=(0, head_radius - head_radius_penetration))\n",
    "        .circle(head_radius)\n",
    "        .extrude(height, both=True)\n",
    "    )\n",
    "    y_depth = arc_box.faces(\"<Y\").val().Center().y\n",
    "    return arc_box.cut(arc_cyclinder).translate((0, -y_depth))\n",
    "\n",
    "\n",
    "def create_cutout_cylinder(\n",
    "    radius: float,\n",
    "    height: float,\n",
    "    penetration: float,\n",
    "):\n",
    "    return (\n",
    "        cq.Workplane(\"XY\", origin=(0, radius - penetration))\n",
    "        .circle(radius)\n",
    "        .extrude(height / 2, both=True)\n",
    "    )\n",
    "\n",
    "\n",
    "def create_headbox(\n",
    "    width: float,\n",
    "    height: float,\n",
    "    depth: float,\n",
    "    head_radius: float,\n",
    "    head_radius_penetration: float,\n",
    "    board_hole_spacing: Tuple[float, float],\n",
    "    through_hole_width: float,\n",
    "    board_mount_clearance: float,\n",
    "):\n",
    "    arc = create_arc(\n",
    "        width=width,\n",
    "        height=height,\n",
    "        head_radius=head_radius,\n",
    "        head_radius_penetration=head_radius_penetration,\n",
    "    )\n",
    "    box = cq.Workplane(\"XZ\").box(width, height, depth, centered=(True, True, False))\n",
    "    cutout_cylinder = create_cutout_cylinder(\n",
    "        radius=3,\n",
    "        height=height / 2,\n",
    "        penetration=0.75,\n",
    "    )\n",
    "    box = box.union(arc).cut(cutout_cylinder)\n",
    "    through_hole = (\n",
    "        cq.Workplane(\"XZ\")\n",
    "        .box(through_hole_width, height / 4, depth, centered=(True, True, False))\n",
    "        .edges(\"|Y\")\n",
    "        .fillet(0.2)\n",
    "    )\n",
    "    box = box.cut(through_hole)\n",
    "    strap_width = 0.5\n",
    "    for strap_position in (-width / 2, width / 2 - strap_width):\n",
    "        strap_guide = create_strap_guide(\n",
    "            height=height / 4,\n",
    "            width=strap_width,\n",
    "            depth=0.4,\n",
    "            strap_clearance=0.2,\n",
    "        ).translate((strap_position, -depth, 0))\n",
    "        box = box.union(strap_guide)\n",
    "    board_hole_spacing_x, board_hole_spacing_z = board_hole_spacing\n",
    "    board_hole_positions = [\n",
    "        (board_hole_spacing_x / 2, board_hole_spacing_z / 2),\n",
    "        (-board_hole_spacing_x / 2, board_hole_spacing_z / 2),\n",
    "        (-board_hole_spacing_x / 2, -board_hole_spacing_z / 2),\n",
    "        (board_hole_spacing_x / 2, -board_hole_spacing_z / 2),\n",
    "    ]\n",
    "    for x, z in board_hole_positions:\n",
    "        box = box.union(\n",
    "            create_screw_mount(\n",
    "                hole_diameter=0.26,\n",
    "                hole_padding=0.2,\n",
    "                depth=board_mount_clearance,\n",
    "            ).translate((x, -0.5, z))\n",
    "        )\n",
    "    return box\n",
    "\n",
    "\n",
    "create_headbox(\n",
    "    10,\n",
    "    10,\n",
    "    1,\n",
    "    8.5,\n",
    "    2,\n",
    "    board_hole_spacing=(7.415, 7.9),\n",
    "    through_hole_width=0.75,\n",
    "    board_mount_clearance=1.25,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_battery_holder(\n",
    "    battery_width: float,\n",
    "    battery_height: float,\n",
    "    battery_depth: float,\n",
    "    corner_extent: float = 1,\n",
    "    corner_thickness: float = 0.2,\n",
    "):\n",
    "    width = battery_width + 2 * corner_thickness\n",
    "    height = battery_height + 2 * corner_thickness\n",
    "    box = cq.Workplane(\"XZ\").box(\n",
    "        width,\n",
    "        height,\n",
    "        battery_depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    v_cut_box = cq.Workplane(\"XZ\").box(\n",
    "        width - 2 * corner_extent,\n",
    "        height,\n",
    "        battery_depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    h_cut_box = cq.Workplane(\"XZ\").box(\n",
    "        width,\n",
    "        height - 2 * corner_extent,\n",
    "        battery_depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    inner_box = cq.Workplane(\"XZ\").box(\n",
    "        battery_width,\n",
    "        battery_height,\n",
    "        battery_depth,\n",
    "        centered=(True, True, False),\n",
    "    )\n",
    "    box = box.cut(inner_box).cut(v_cut_box).cut(h_cut_box)\n",
    "    return box\n",
    "\n",
    "\n",
    "create_battery_holder(6, 3.6, 0.8)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "def create_wedge(\n",
    "    radius: float,\n",
    "    angle: float,\n",
    "    depth: float\n",
    "):\n",
    "    angle_rads = math.radians(90 - angle / 2)\n",
    "    x_offset = radius * math.cos(angle_rads)\n",
    "    y_offset = radius * math.sin(angle_rads)\n",
    "    return (\n",
    "        cq.Workplane(\"XY\")\n",
    "        .moveTo(0, 0)\n",
    "        .lineTo(x_offset, y_offset)\n",
    "        .threePointArc((0, radius), (-x_offset, y_offset))\n",
    "        .close()\n",
    "        .extrude(depth)\n",
    "    )\n",
    "\n",
    "\n",
    "create_wedge(5, 45, 1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_kemo_tweeter_fill(\n",
    "    inner_diameter: float,\n",
    "    outer_diameter: float,\n",
    "    depth: float,\n",
    "    bottom_wedge_angle: float\n",
    "):\n",
    "    inner_radius = inner_diameter / 2\n",
    "    outer_radius = outer_diameter / 2\n",
    "    wp = cq.Workplane(\"XZ\")\n",
    "    cone = cq.Solid.makeCone(inner_radius, outer_radius, depth)\n",
    "    wedge = create_wedge(outer_radius, bottom_wedge_angle, depth)\n",
    "    wp.add(cone)\n",
    "    wp.add(wedge)\n",
    "    return wp\n",
    "\n",
    "create_kemo_tweeter_fill(31, 41, 10, 75)\n",
    "\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "def create_kemo_testbed():\n",
    "    headband = create_headband_arc(\n",
    "        radius=470/(2*math.pi),\n",
    "        thickness=8,\n",
    "        extension=1,\n",
    "        height=45,\n",
    "    )\n",
    "    kemo = create_kemo_tweeter_fill(\n",
    "        inner_diameter=35,\n",
    "        outer_diameter=41,\n",
    "        depth=11,\n",
    "        bottom_wedge_angle=90,\n",
    "    ).rotate((0, 0, 0), (-1, 0, 0), 90).translate((0, -5, 0))\n",
    "    box = cq.Workplane(\"XZ\").box(50, 100, 100, centered=(True, True, False)).translate((0, 100, 0))\n",
    "    headband_fragment = box.intersect(headband)\n",
    "    headband_fragment = headband_fragment.translate(-headband_fragment.val().Center())\n",
    "    return headband_fragment.cut(kemo)\n",
    "\n",
    "\n",
    "ktb = create_kemo_testbed()\n",
    "ktb.val().exportStl(\"./exports/ktb.stl\")\n",
    "\n",
    "ktb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "80c7bf4bcbc4413a98f0ae0b24fa6220",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "CadViewerWidget(anchor=None, cad_width=800, glass=True, height=600, pinning=False, theme='light', title=None, â€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<div></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from headset.headband import create_mic_clip\n",
    "\n",
    "base = cq.Workplane(\"XZ\").box(2, 10, 10, centered=(True, True, False))\n",
    "center = base.faces(\"<X\").val().Center()\n",
    "clip = (\n",
    "    create_mic_clip(\n",
    "        clearance=2.75,\n",
    "        height=6,\n",
    "        protrusion=10,\n",
    "        thickness=1,\n",
    "    )\n",
    "    .translate(center)\n",
    "    .translate((-6 / 2, 0, 0))\n",
    ")\n",
    "\n",
    "mic_clip_testbed = base.union(clip)\n",
    "mic_clip_testbed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mic_clip_testbed.val().exportStl(\"./exports/micClipTestbed275.stl\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "robin-headset-pueixTSH-py3.11",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
